USE extrabits_junior_db;

-- Insert courses mapping to the newly inserted classes (IDs 8 to 13)

INSERT INTO courses (class_id, course_name, slug, short_description, full_description, duration, fees, level, is_featured, status, created_at) VALUES 
(8, 'Basic MS Office & Scratch', 'basic-ms-office-scratch', 'Learn essential MS Office applications and start visual programming with Scratch.', 'This course introduces 7th standard students to intermediate word processing, basic spreadsheets, and the fundamentals of logic building using Scratch visual programming. Students will create interactive stories and games while mastering presentation skills.\n\n• Advanced MS Word formatting\n• Excel basics and simple formulas\n• PowerPoint animations\n• Introduction to Scratch blocks\n• Creating basic games and animations', '4 months', 5500.00, 'Beginner', 0, 'active', NOW()),
(9, 'Web Design & Graphics Intro', 'web-design-graphics-intro', 'Build your first web pages and learn the basics of digital design.', 'Designed for 8th standard students, this course covers the essentials of HTML, CSS, and basic graphic design using beginner-friendly tools.\n\n• HTML tags and structure\n• CSS styling basics\n• Introduction to CorelDraw/Canva\n• Creating logos and posters\n• Building a basic 3-page website', '6 months', 6500.00, 'Intermediate', 1, 'active', NOW()),
(10, 'Python & Logic Building', 'python-logic-building', 'Step into text-based programming with Python and develop strong algorithmic thinking.', 'Perfect for 9th standard students, this course transitions from visual to text-based coding using Python. Focuses on core logic and simple applications.\n\n• Python syntax and variables\n• Control structures (if/else, loops)\n• Functions and modules\n• Basic data structures (lists, dictionaries)\n• Simple text-based games and calculators', '6 months', 7500.00, 'Intermediate', 1, 'active', NOW()),
(11, 'Advanced Excel & C Programming', 'advanced-excel-c-programming', 'Master advanced spreadsheet functions and learn the foundational C programming language.', 'A critical course for 10th standard students balancing board prep with IT skills. Covers complex data handling and core C programming.\n\n• Advanced Excel (VLOOKUP, Pivot Tables)\n• Data analysis basics\n• Introduction to C language\n• Pointers and memory management basics\n• Project: Student Data Management System', '6 months', 8000.00, 'Advanced', 0, 'active', NOW()),
(12, 'C++ & Database Fundamentals', 'cpp-database-fundamentals', 'Deep dive into Object-Oriented Programming and SQL databases.', 'Geared towards 11th standard students, this course covers the standard curriculum requirements for computer science streams.\n\n• OOP concepts in C++ (Classes, Objects, Inheritance)\n• File handling in C++\n• Introduction to RDBMS\n• Basic SQL queries (SELECT, INSERT, UPDATE, DELETE)\n• Integration concepts', '8 months', 9500.00, 'Advanced', 1, 'active', NOW()),
(13, 'Java & Full Stack Basics', 'java-full-stack-basics', 'Prepare for professional IT fields with Java programming and web application basics.', 'The ultimate preparation for 12th standard students looking to build a career in software development. Covers robust programming and web architecture.\n\n• Core Java concepts\n• Exception handling and Multithreading\n• Introduction to Frontend (HTML/CSS/JS refresher)\n• Basic Backend concepts\n• Final Project: Mini Web Application', '8 months', 11000.00, 'Advanced', 1, 'active', NOW());
