import React from 'react';
import { Metadata, ResolvingMetadata } from 'next';
import CourseDetailsClient from './CourseDetailsClient';
import { JsonLd, BreadcrumbSchema } from '@/components/seo/JsonLd';

interface Props {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}

async function getCourse(id: string) {
  try {
    const res = await fetch(`http://localhost:8000/api/courses/read_single.php?id=${encodeURIComponent(id)}`, {
      cache: 'no-store' // Force fresh fetch to bypass stale cache
    });
    if (!res.ok) return null;
    const data = await res.json();
    return data.success ? data.data : null;
  } catch (error) {
    return null;
  }
}

export async function generateMetadata(
  props: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
  const params = await props.params;
  const searchParams = await props.searchParams;
  const course = await getCourse(params.id);
  
  if (!course) {
    return { title: 'Course Not Found' };
  }

  let title = course.seo_title || course.course_name;
  let description = course.seo_description || course.short_description;
  const keywords = course.seo_keywords || course.meta_keywords || '';
  const city = typeof searchParams.city === 'string' ? searchParams.city : '';

  // Local SEO dynamic injection
  if (course.local_seo_enabled && city) {
    // Capitalize city
    const capitalizedCity = city.charAt(0).toUpperCase() + city.slice(1);
    
    // Inject city if it doesn't already exist in the string
    if (!title.toLowerCase().includes(capitalizedCity.toLowerCase())) {
      title = `${title} in ${capitalizedCity}`;
    }
    if (description && !description.toLowerCase().includes(capitalizedCity.toLowerCase())) {
      description = `${description} Available in ${capitalizedCity}, Gujarat.`;
    }
  }

  const baseCanonical = course.canonical_url || `https://extrabitsjunior.com/courses/${course.primary_slug || course.slug_title}`;

  return {
    title,
    description,
    keywords,
    alternates: {
      canonical: baseCanonical, // Always point to the base URL to prevent duplicate content
    },
    openGraph: {
      title: course.og_title || title,
      description: course.og_description || description,
      url: baseCanonical,
      images: [
        {
          url: course.thumbnail_image ? `https://extrabitsjunior.com/uploads/courses/${course.thumbnail_image}` : 'https://extrabitsjunior.com/default-og.jpg',
          width: 1200,
          height: 630,
        }
      ],
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: course.twitter_title || title,
      description: course.twitter_description || description,
    }
  };
}

import { redirect } from 'next/navigation';

export default async function CoursePage(props: Props) {
  const params = await props.params;
  const searchParams = await props.searchParams;
  const course = await getCourse(params.id);
  const city = typeof searchParams.city === 'string' ? searchParams.city : '';

  if (!course) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#FDFBF7]">
        <h1 className="text-2xl font-bold text-zinc-900">Course Not Found</h1>
      </div>
    );
  }

  const expectedSlug = course.primary_slug || course.slug_title;
  if (expectedSlug && params.id !== expectedSlug) {
    const query = city ? `?city=${city}` : '';
    redirect(`/courses/${expectedSlug}${query}`);
  }

  // Schema Generation
  let schemaData = null;
  if (course.schema_json) {
    try {
      schemaData = typeof course.schema_json === 'string' ? JSON.parse(course.schema_json) : course.schema_json;
    } catch(e) {}
  }

  // Fallback schema if not generated by AI
  if (!schemaData) {
    schemaData = {
      "@context": "https://schema.org",
      "@type": "Course",
      "name": course.course_name,
      "description": course.short_description,
      "provider": {
        "@type": "EducationalOrganization",
        "name": "Extrabits Junior",
        "sameAs": "https://extrabitsjunior.com"
      }
    };
  }

  const breadcrumbs = [
    { name: 'Home', url: 'https://extrabitsjunior.com' },
    { name: 'Courses', url: 'https://extrabitsjunior.com/courses' },
    { name: course.course_name, url: `https://extrabitsjunior.com/courses/${course.primary_slug || course.slug_title}` }
  ];

  return (
    <>
      <JsonLd data={schemaData} />
      <BreadcrumbSchema items={breadcrumbs} />
      <CourseDetailsClient initialData={course} city={city} idParam={params.id} />
    </>
  );
}
